### ISSUE TITLE
NEMUtil.php Missing

### ISSUE THREAD

**Issue by iamNEMonic** [tomotomo9696/NEMTools_PHP#1]
Failed to initialize because there is one missing file which is the NEMUtil.php

**Comment by tonydspaniard** [comment]
@iamNEMonic Found it here buddy: https://github.com/tipxem/tipxem/blob/master/nem/NEMUtil.php

**Comment by tonydspaniard** [comment]
for those who needed: https://github.com/tipxem/tipxem/tree/master/nem

**Comment by tomotomo9696** [comment]
Oops, I did not notice that it was missing.
Thank you!

**Comment by tonydspaniard** [comment]
Thanks @tomotomo9696 ...
